version: '3'
services:
  nginx:
    image: nginx:1.12
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php-fpm
  php-fpm:
    build: "./docker/php-fpm/"
    volumes:
      - ./:/var/www/html
      - ~/.aws/:/var/www/.aws/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zzmyphp-fpm.conf
